### ISSUE TITLE
What is triggering the "Heading Home" webhook?

### ISSUE THREAD

**Issue by greg-nyc** [thejeffreystone/home-assistant-configuration#77]
Thanks for posting your config. I'm trying to follow along with some of your presence work, but I haven't figured out how HA is sensing your destination. It looks like there's an API call, but I can't figure out what's triggering it. What is triggering the `jeff_heading_home` webhook call in this automation?

```
  - id: '1550109528753'
    alias: Jeff Is Heading Home
    initial_state: true
    trigger:
    - platform: webhook
      webhook_id: jeff_heading_home
    condition: []
    action:
    - service: script.jeff_destination_home
    - service: script.ah_report
      data:
        call_interurption: 1
        call_jeff_headed_home: 1
```
